In [122]:
#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")


In [123]:
# Load the dataset
df = pd.read_csv("C:\\Users\\vasud\\Downloads\\Salary Data.csv")
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [124]:
# remove unnecessary columns
# Here we are dropping the columns that are not needed for the regression analysis
new_df=df.drop(["Age","Gender","Education Level","Job Title"],axis=1)
new_df

Years of Experience    Salary
0                    5.0   90000.0
1                    3.0   65000.0
2                   15.0  150000.0
3                    7.0   60000.0
4                   20.0  200000.0
..                   ...       ...
370                  8.0   85000.0
371                 19.0  170000.0
372                  2.0   40000.0
373                  7.0   90000.0
374                 15.0  150000.0

[375 rows x 2 columns]

In [125]:
# Check for null values in the new DataFrame
new_df.isnull().sum()

Years of Experience    2
Salary                 2
dtype: int64

In [126]:
#filling the null values with median values
new_df["Salary"].fillna(new_df["Salary"].median(),inplace=True)
new_df["Years of Experience"].fillna(new_df["Years of Experience"].median(),inplace=True)

In [127]:
# Check for null values in the new DataFrame
new_df.isnull().sum()

Years of Experience    0
Salary                 0
dtype: int64

In [128]:
# Split the data into features and target variable
#dependent variable or independent variable
x= np.array(new_df["Years of Experience"]).reshape(-1, 1)
y= np.array(new_df["Salary"])


In [129]:
x

array([[ 5. ],
       [ 3. ],
       [15. ],
       [ 7. ],
       [20. ],
       [ 2. ],
       [12. ],
       [ 4. ],
       [ 1. ],
       [10. ],
       [ 3. ],
       [18. ],
       [ 6. ],
       [14. ],
       [ 2. ],
       [16. ],
       [ 7. ],
       [12. ],
       [ 0. ],
       [22. ],
       [ 5. ],
       [19. ],
       [ 2. ],
       [ 9. ],
       [13. ],
       [ 3. ],
       [11. ],
       [ 1. ],
       [15. ],
       [ 6. ],
       [25. ],
       [ 4. ],
       [ 3. ],
       [10. ],
       [20. ],
       [ 2. ],
       [ 7. ],
       [14. ],
       [ 1. ],
       [21. ],
       [ 5. ],
       [18. ],
       [ 3. ],
       [ 8. ],
       [13. ],
       [ 2. ],
       [ 5. ],
       [16. ],
       [11. ],
       [ 0. ],
       [22. ],
       [ 7. ],
       [12. ],
       [19. ],
       [ 3. ],
       [ 9. ],
       [ 2. ],
       [17. ],
       [ 4. ],
       [ 7. ],
       [23. ],
       [ 3. ],
       [12. ],
       [21. ],
       [ 1. ],
       [10. ],
       [19

In [130]:
y

array([ 90000.,  65000., 150000.,  60000., 200000.,  55000., 120000.,
        80000.,  45000., 110000.,  75000., 140000.,  65000., 130000.,
        40000., 125000.,  90000., 115000.,  35000., 180000.,  80000.,
       190000.,  50000.,  60000., 140000.,  45000., 110000.,  40000.,
       140000.,  90000., 250000.,  55000.,  75000.,  65000., 170000.,
        45000.,  60000., 115000.,  40000., 160000.,  80000., 190000.,
        60000.,  45000., 130000.,  40000.,  75000., 180000., 120000.,
        35000., 130000.,  85000.,  60000., 200000.,  50000.,  95000.,
        65000., 140000.,  55000., 105000., 170000.,  50000.,  80000.,
       180000.,  35000.,  90000., 120000.,  45000.,  90000., 150000.,
        65000.,  70000., 190000.,  40000., 120000.,  95000., 160000.,
       100000., 180000.,  55000.,  70000.,  80000.,  30000., 250000.,
        40000.,  95000.,  45000.,  80000., 135000.,  55000., 120000.,
        40000., 105000., 170000.,  75000.,  65000., 160000.,  35000.,
        90000., 1100

In [131]:
# splitting the data into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [132]:
x_train.shape,x_test.shape

((262, 1), (113, 1))

In [133]:
y_train.shape,y_test.shape

((262,), (113,))

In [134]:
#model building
from sklearn.linear_model import LinearRegression
LinReg=LinearRegression()
LinReg.fit(x_train,y_train)

LinearRegression()

In [135]:
#model pridection
y_pred=LinReg.predict(x_test)

In [136]:
y_pred

array([ 46217.59073722,  53044.71199126,  39390.46948317,  94007.43951551,
       134970.16703976, 203241.37958018,  39390.46948317,  53044.71199126,
        53044.71199126,  94007.43951551, 107661.68202359, 162278.65205593,
        80353.19700743, 182760.01581805,  59871.8332453 , 128143.04578572,
        32563.34822913,  80353.19700743, 162278.65205593,  94007.43951551,
        46217.59073722,  80353.19700743,  59871.8332453 , 114488.80327763,
       169105.77330997,  46217.59073722,  94007.43951551, 128143.04578572,
        80353.19700743,  46217.59073722,  46217.59073722,  53044.71199126,
        94007.43951551,  46217.59073722,  87180.31826147,  53044.71199126,
       114488.80327763, 155451.53080189,  53044.71199126,  53044.71199126,
       141797.2882938 , 134970.16703976, 175932.89456401, 134970.16703976,
        87180.31826147,  94007.43951551, 134970.16703976,  42804.0301102 ,
       107661.68202359,  66698.95449934, 121315.92453168,  94007.43951551,
       175932.89456401, 1

In [137]:
act_pred_df = pd.DataFrame({"Actual":y_test,
                            "Predicted":y_pred})
act_pred_df

Actual      Predicted
0     40000.0   46217.590737
1     50000.0   53044.711991
2     40000.0   39390.469483
3    110000.0   94007.439516
4    150000.0  134970.167040
..        ...            ...
108   60000.0   59871.833245
109  100000.0   94007.439516
110   40000.0   46217.590737
111   40000.0   46217.590737
112   40000.0   46217.590737

[113 rows x 2 columns]

In [138]:
# model accuracy
LinReg.score(x_train,y_train)*100

85.17974681699484

In [139]:
# model accuracy
LinReg.score(x_test,y_test)*100

89.17938406537392

In [140]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)*100

89.17938406537392

In [146]:
new_array=np.array([[7]])
new_array

array([[7]])

In [148]:
pred= LinReg.predict(new_array)
pred

array([80353.19700743])