In [2]:
pip install numpy

  Using cached numpy-2.3.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.1-cp313-cp313-win_amd64.whl (12.7 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
#dimentional array

zero_array=np.array(58)
print(zero_array)
print(type(zero_array))
print(zero_array.ndim)
print(zero_array.shape)


58
<class 'numpy.ndarray'>
0
()


In [7]:
one_d_array=np.array([2,4,6,7])
print(one_d_array)
print(type(one_d_array))
print(one_d_array.ndim)
print(one_d_array.shape)


[2 4 6 7]
<class 'numpy.ndarray'>
1
(4,)


In [11]:
two_array =np.array([[2,4],[6,7]])
print(two_array)
print(type(two_array))
print(two_array.ndim)
print(two_array.shape)

[[2 4]
 [6 7]]
<class 'numpy.ndarray'>
2
(2, 2)


In [13]:
two_array =np.array([[2,"4",6],[6,8,7]])
print(two_array)
print(type(two_array))
print(two_array.ndim)
print(two_array.shape)
print(two_array.dtype)

[['2' '4' '6']
 ['6' '8' '7']]
<class 'numpy.ndarray'>
2
(2, 3)
<U21


In [8]:
py_arr2=np.array([[45,23,65,67],[2,5,67,8],[55,66,77,88]])
print(py_arr2)
print(py_arr2.shape)

[[45 23 65 67]
 [ 2  5 67  8]
 [55 66 77 88]]
(3, 4)


In [16]:
threed_array=np.array([[[1,2,3],[2,3,4]],[[4,5,6],[7,8,9]]])
print(threed_array)
print(threed_array.ndim)
print(threed_array.shape)

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [7 8 9]]]
3
(2, 2, 3)


In [17]:
threed_array=np.array([[[1,2,3],[2,3,4],[1,2,3,]],
                       [[4,5,6],[7,8,9],[1,2,3]],
                       [[4,5,6],[6,7,8],[6,7,8]]])
print(threed_array)
print(threed_array.ndim)
print(threed_array.shape)

[[[1 2 3]
  [2 3 4]
  [1 2 3]]

 [[4 5 6]
  [7 8 9]
  [1 2 3]]

 [[4 5 6]
  [6 7 8]
  [6 7 8]]]
3
(3, 3, 3)


In [21]:
threed_array=np.array([[[1,2,3],[2,3,4],[1,2,3,]],
                       [[4,5,6],[7,8,9],[1,2,3]],
                       [[4,5,6],[6,7,8],[6,7,8]]],ndmin=10,dtype=str)
print(threed_array)
print(threed_array.ndim)
print(threed_array.shape)

[[[[[[[[[['1' '2' '3']
         ['2' '3' '4']
         ['1' '2' '3']]

        [['4' '5' '6']
         ['7' '8' '9']
         ['1' '2' '3']]

        [['4' '5' '6']
         ['6' '7' '8']
         ['6' '7' '8']]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 3, 3, 3)


In [25]:
#Zero array
py_arr=np.zeros((3,3),dtype=int)
print(py_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [24]:
one_array=np.ones((4,5),dtype=int)
print(one_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [27]:
arrag=np.arange(9,15,)
print(arrag)
print(arrag.ndim)
print(arrag.shape)
reshap_arr=np.reshape(arrag,shape=(3,2))
print(reshap_arr)

[ 9 10 11 12 13 14]
1
(6,)
[[ 9 10]
 [11 12]
 [13 14]]


In [30]:
array=np.linspace(0,1,num=10)
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [31]:
array=np.logspace(0,1,num=10)
print(array)

[ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


In [32]:
threed_array=np.array([[[1,2,3],[2,3,4],[1,2,3,]],
                       [[4,5,6],[7,8,9],[1,2,3]],
                       [[4,5,6],[6,7,8],[6,7,8]]],ndmin=1,dtype=str)
print(threed_array)
print(threed_array.ndim)
print(threed_array.shape)

[[['1' '2' '3']
  ['2' '3' '4']
  ['1' '2' '3']]

 [['4' '5' '6']
  ['7' '8' '9']
  ['1' '2' '3']]

 [['4' '5' '6']
  ['6' '7' '8']
  ['6' '7' '8']]]
3
(3, 3, 3)


In [ ]:
#mathamatic operation add
a=np.array([[3,6],[7,8]])
b=np.array([[2,5],[3,7]])
sum=a+b
print(sum)
print(np.add(a,b))

[[ 5 11]
 [10 15]]
[[ 5 11]
 [10 15]]


In [35]:
a=np.array([[3,6],[7,8]])
b=np.array([[2,5],[3,7]])
sum=a-b
print(sum)
print(np.subtract(a,b))

[[1 1]
 [4 1]]
[[1 1]
 [4 1]]


In [36]:
a=np.array([[3,6],[7,8]])
b=np.array([[2,5],[3,7]])
sum=a*b
print(sum)
print(np.multiply(a,b))

[[ 6 30]
 [21 56]]
[[ 6 30]
 [21 56]]


In [37]:
a=np.array([[3,6],[7,8]])
b=np.array([[2,5],[3,7]])
sum=a/b
print(sum)
print(np.divide(a,b))

[[1.5        1.2       ]
 [2.33333333 1.14285714]]
[[1.5        1.2       ]
 [2.33333333 1.14285714]]


In [40]:
a=np.array([[[3,6],[7,8]],[[7,9],[9,3]]])
b=np.array([[[6,8],[12,56]],[[23,21],[13,15]]])
sum=a+b
print(sum)
print("--"*50)
print(np.add(a,b))

[[[ 9 14]
  [19 64]]

 [[30 30]
  [22 18]]]
----------------------------------------------------------------------------------------------------
[[[ 9 14]
  [19 64]]

 [[30 30]
  [22 18]]]


In [41]:
a=np.array([[[3,6],[7,8]],[[7,9],[9,3]]])
b=np.array([[[6,8],[12,56]],[[23,21],[13,15]]])
sum=a-b
print(sum)
print("--"*50)
print(np.subtract(a,b))

[[[ -3  -2]
  [ -5 -48]]

 [[-16 -12]
  [ -4 -12]]]
----------------------------------------------------------------------------------------------------
[[[ -3  -2]
  [ -5 -48]]

 [[-16 -12]
  [ -4 -12]]]


In [ ]:
a=np.array([[[3,6],[7,8]],[[7,9],[9,3]]])
b=np.array([[[6,8],[12,56]],[[23,21],[13,15]]])
sum=a*b
print(sum)
print("--"*50)
print(np.multiply(a,b))

In [ ]:
a=np.array([[[3,6],[7,8]],[[7,9],[9,3]]])
b=np.array([[[6,8],[12,56]],[[23,21],[13,15]]])
sum=a/b
print(sum)
print("--"*50)
print(np.divide(a,b))

In [6]:
#indexing
import numpy as np
one_darray=np.array([40,63,23])
print(one_darray[1])
print(one_darray[1])
print(one_darray[1])
print(one_darray[-1])

63
63
63
23


In [11]:
two_darray=np.array([[40,63,23],[2,5,7],[4,7,9]])
print(two_darray)
print(two_darray[1])
print(two_darray[1][0])
print(two_darray[1,:2])
print(two_darray[2,1:])
print(two_darray[0:2,:2])
print(two_darray[0:2][1:])


[[40 63 23]
 [ 2  5  7]
 [ 4  7  9]]
[2 5 7]
2
[2 5]
[7 9]
[[40 63]
 [ 2  5]]
[[2 5 7]]


In [20]:
three_darray=np.array([[[40,63,23],[2,5,7]],
                       [[4,7,9],[7,8,9]],
                       [[44,55,66],[22,22,33]]])
print(three_darray)
print(three_darray.shape)
print("1-"*50)
print(three_darray[0])
print(three_darray[0][1])
print(three_darray[0][1][1])
print("2-"*50)
print(three_darray[1:])
print("3-"*50)
print(three_darray[1:][1:][1:])
print("4-"*50)





[[[40 63 23]
  [ 2  5  7]]

 [[ 4  7  9]
  [ 7  8  9]]

 [[44 55 66]
  [22 22 33]]]
(3, 2, 3)
1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-
[[40 63 23]
 [ 2  5  7]]
[2 5 7]
5
2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-
[[[ 4  7  9]
  [ 7  8  9]]

 [[44 55 66]
  [22 22 33]]]
3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-
[]
4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-


In [15]:
import numpy as np
one_darray=np.array([40,63,23])
print(one_darray)
one_darray[1]=55
print(one_darray)

[40 63 23]
[40 55 23]


In [16]:
import numpy as np
one_darray=np.array([40,63,23])
print(one_darray)
one_darray[0:]=[2,4,6]
print(one_darray)

[40 63 23]
[2 4 6]


In [27]:
two_d=np.array([[4,6,7],[8,3,6]])
print(two_d)
print(two_d[two_d<=6])
print(two_d[two_d>5])

[[4 6 7]
 [8 3 6]]
[4 6 3 6]
[6 7 8 6]


In [ ]:
two_d=np.array([[4,6,7],
                [8,3,6],
                [55,88,99]])
print(two_d.min())
print(two_d.max())
print(two_d.mean())
print(np.median(two_d))
print(np.std(two_d))
print(np.var(two_d))
print(two_d.argmax(axis=0))
print(two_d.argmax(axis=1))

3
99
30.666666666666668
7.0
36.99249173068022
1368.4444444444443
[2 2 2]
[2 0 2]


In [ ]:
three_darray=np.array([[[40,63,23],[2,5,7]],
                       [[4,7,9],[7,8,9]]])
                       
print(three_darray)
print(three_darray.argmin(axis=1))#col
print(three_darray.argmin(axis=0))#row

[[[40 63 23]
  [ 2  5  7]]

 [[ 4  7  9]
  [ 7  8  9]]]
[[1 1 1]
 [0 0 0]]
[[1 1 1]
 [0 0 0]]


In [ ]:
#array joining
a=np.array([3,5,7])
b=np.array([1,5,8])
concat=np.concatenate((a,b))

print(concat)

[3 5 7 1 5 8]


In [49]:
a=np.array([[3,5,7],[4,8,0]])
b=np.array([[1,5,8],[9,10,11]])
concat1=np.concatenate((a,b),axis=1)
concat0=np.concatenate((a,b),axis=0)
print(concat1)
print(concat0)

[[ 3  5  7  1  5  8]
 [ 4  8  0  9 10 11]]
[[ 3  5  7]
 [ 4  8  0]
 [ 1  5  8]
 [ 9 10 11]]


In [ ]:
a=np.array([[3,5,7],[4,8,0]])
b=np.array([[1,5,8],[9,10,11]])
print(a)
print(b) #not aplide
stack=np.stack((a,b))
stack0=np.stack((a,b),axis=0)
stack1=np.stack((a,b),axis=1)
print(stack)
print("--"*50)
print(stack0)
print("--"*50)
print(stack1)


[[3 5 7]
 [4 8 0]]
[[ 1  5  8]
 [ 9 10 11]]
[[[ 3  5  7]
  [ 4  8  0]]

 [[ 1  5  8]
  [ 9 10 11]]]
----------------------------------------------------------------------------------------------------
[[[ 3  5  7]
  [ 4  8  0]]

 [[ 1  5  8]
  [ 9 10 11]]]
----------------------------------------------------------------------------------------------------
[[[ 3  5  7]
  [ 1  5  8]]

 [[ 4  8  0]
  [ 9 10 11]]]


In [54]:
a=np.array([3,5,7])
b=np.array([1,5,8])
print(a)
print(b)
stack=np.stack((a,b))
stack1=np.vstack((a,b))
stack2=np.hstack((a,b))

print(stack)
print(stack1)
print(stack2)

[3 5 7]
[1 5 8]
[[3 5 7]
 [1 5 8]]
[[3 5 7]
 [1 5 8]]
[3 5 7 1 5 8]


In [56]:
a=np.array([[3,5,7],[4,8,0]])
b=np.array([[1,5,8],[9,10,11]])
print(a)
print(b) #not aplide

stack0=np.vstack((a,b))
stack1=np.hstack((a,b))

print("--"*50)
print(stack0)
print("--"*50)
print(stack1)

[[3 5 7]
 [4 8 0]]
[[ 1  5  8]
 [ 9 10 11]]
----------------------------------------------------------------------------------------------------
[[ 3  5  7]
 [ 4  8  0]
 [ 1  5  8]
 [ 9 10 11]]
----------------------------------------------------------------------------------------------------
[[ 3  5  7  1  5  8]
 [ 4  8  0  9 10 11]]


In [58]:
a=np.array([[3,5,7],[4,8,0]])
c=np.transpose(a)
print(c)

[[3 4]
 [5 8]
 [7 0]]


In [59]:
a=np.array([[3,5,7],[4,8,0]])
c=a.T
print(c)

[[3 4]
 [5 8]
 [7 0]]


In [ ]:
import numpy as np
a=np.array([[3,5,7],[4,8,0]])
z=np.sort(a)
y=np.sort(a,d)
print(z)

[[3 5 7]
 [0 4 8]]
